[package]
name = "robotics_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, optional = true }
libm = "0.2"

[features]
default = ["std"]
std = []
serde = ["dep:serde"]
